(function(k){if(typeof _ACTrackerz==="undefined"){_ACTrackerz=null;var g,f=_ACTrackerz=function(a){return new f.prototype.init(a)};f.extend=function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b]);return a};f.extend(f,{idle:[1,1],joinParameters:function(a,c){var b=[],d;if(c===",")for(d in a)a.hasOwnProperty(d)&&a[d]!==""&&a[d]!=k&&Array.prototype.push.call(b,a[d]);else if(c==="&")for(d in a)a.hasOwnProperty(d)&&a[d]!==""&&a[d]!=k&&Array.prototype.push.call(b,d+"="+a[d]);return b.join(c)},getCurrentUrl:function(){var a=
"";try{a=top.location.href}catch(c){try{a=document.referrer}catch(b){}}return encodeURIComponent(a)},getPreviousUrl:function(){var a="";try{a=top.document.referrer}catch(c){}return encodeURIComponent(a)},getQueryString:function(a){var c,b={},d,h,e;if(!f.queryString){try{c=top.location.search}catch(g){c=location.search}if(c){c=c.substr(1);c=c.split("&");for(d=0,h=c.length;d<h;d++)e=c[d].split("="),e.length===2&&(b[e[0]]=e[1])}f.queryString=b}return f.queryString[a]},getCookieEnabled:function(){return navigator.cookieEnabled?
1:0},getFlashVersion:function(){var a="0,0,0,0";try{navigator.plugins&&navigator.plugins["Shockwave Flash"]?a=navigator.plugins["Shockwave Flash"].description:window.ActiveXObject&&new ActiveXObject("ShockwaveFlash.ShockwaveFlash")&&(a=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version"))}catch(c){}a=a.match(/\d+/g);return a[0]},send:function(a){var c=document.createElement("img"),b=document.getElementsByTagName("script")[0];c.style.display="none";b.parentNode.insertBefore(c,
b);c.src=a},mappimg:function(){if(location.protocol!="https:"){var a=document.createElement("iframe"),c=document.body?document.body.firstChild:document.getElementsByTagName("script")[0];a.style.display="none";a.src="http://static.acs86.com/actmap.htm";c.parentNode.insertBefore(a,c)}},load:function(a,c,b,d,f){var e,g=/loaded|complete/i,j="ac_script_$"+Math.ceil(Math.random()*1E10);c?(e=document.createElement("script"),e.type="text/javascript",e.async=!0,e.charset="utf-8",e.id=j,e.src=a,a=document.getElementsByTagName("script")[0],
a.parentNode.insertBefore(e,a)):(window.ActiveXObject&&(g=/complete/i),document.write('<script type="text/javascript" charset="utf-8" src="'+a+'" id="'+j+'"><\/script>'));if(e=document.getElementById(j))e.onload=e.onreadystatechange=function(){var h;if(!e.readyState||e.readyState.match(g))if(typeof b==="function"&&b(),f=b=null,e&&e.parentNode)h=e.onload=e.onreadystatechange=null,e=h},e.onerror=function(){typeof f==="function"&&f();f=b=null};d&&setTimeout(function(){if(e)typeof f==="function"&&f(),
d=f=null,e.src="javascript:void(0)"},d)},getTopDomain:function(a){if(!arguments.callee.domain){for(var c=(a||location.hostname).split("."),b=/com|edu|gov|int|mil|net|org|biz|info|pro|name|museum|coop|aero|xxx|idv/,d=c.length-1,f=c.length-1,e=0;d>-1;d--)if(b.test(c[d])){f=d;break}else/\d+/.test(c[d])&&e++;c.length==e&&(f=1);arguments.callee.domain=c.slice(f-1).join(".")}return arguments.callee.domain},cookie:function(a,c,b){if(typeof c!=="undefined"){if(c===null){c="";b=b||{};b.expires=new Date(1970,
1,1);if(!b.path)b.path="/";if(!b.domain&&g)b.domain=g}a=a+"="+encodeURIComponent(c);b&&(b.path&&(a+="; path="+b.path),b.expires instanceof Date&&(a+="; expires="+b.expires.toGMTString()),b.domain&&(a+="; domain="+b.domain),b.secure&&(a+="; secure"));document.cookie=a}else return RegExp(";?"+a+"=([^;]*);?").test(document.cookie)?decodeURIComponent(RegExp.$1):null},JSON2String:function(a){var c=Object.prototype.toString.call(a).toLowerCase(),b="";if(c=="[object number]")b+=a;else if(c=="[object string]")a=
a.replace(/[\'\"\/\\]/g,"\\$&"),a=a.replace(/\r/g,"\\r"),a=a.replace(/\n/g,"\\n"),a=a.replace(/\t/g,"\\t"),b+='"'+a+'"';else if(c=="[object array]"){b+="[";for(c=0;c<a.length;c++)b+=arguments.callee(a[c]),b+=",";b.lastIndexOf(",")==b.length-1&&(b=b.substring(0,b.length-1));b+="]"}else if(c=="[object object]"){b+="{";for(var d in a)a.hasOwnProperty(d)&&(b+='"'+d+'":',b+=arguments.callee(a[d])+",");b.lastIndexOf(",")==b.length-1&&(b=b.substring(0,b.length-1));b+="}"}return b},JSONStringify:function(a){var c=
"";try{c=f.JSON2String(a)}catch(b){}return c},JSONParse:function(a){var c;try{c=eval("("+a+")")}catch(b){c=null}return c},fc:function(){}});f.prototype={constructor:"_ACTrackerz",jsv:9,init:function(a){if(a.mid){var c,b;this.mid=a.mid;this.st=a.st;this.ecc=window!=top?1:0;if(a.ecc)this.ecc=a.ecc;g="."+f.getTopDomain();if(g.lastIndexOf(".")<1||!/\w/.test(g))g=null;this.mergeCookie();this.trimCookie();c=this.zcookie("actn");this.zcookie("acts");b=this.zcookie("acti");c||this.zcookie("actn","0>0>0>0>0>0",
{domain:g,expires:new Date((new Date).getTime()+15552E6),path:"/"});b||this.zcookie("acti",(new Date).getTime()+""+Math.floor(Math.random()*1E5),{domain:g,expires:new Date((new Date).getTime()+15552E6),path:"/"});if(a.serverbaseurl)this.serverbaseurl=a.serverbaseurl;for(c=0,b=a.ers.length;c<b;c++)this.track(a.ers[c])}},mergeCookie:function(){var a=RegExp("@(\\d+)~([^@]+)@","g"),c=["actn","acti","actis","acts","actr"],b=f.cookie("actn"),d=(new Date).getTime()+2592E6,h={},e=0,i;if(b){if(e=f.cookie("actmapping"))h.actmapping=
{0:[e,d]},f.cookie("actmapping",null);for(e=0;e<c.length;e++)if(b=f.cookie(c[e])){h[c[e]]={};a.lastIndex=0;for(i=a.exec(b);i;)h[c[e]][i[1]]=[i[2],d],i=a.exec(b);f.cookie(c[e],null)}try{f.cookie("acta",f.JSONStringify(h),{domain:g,expires:new Date((new Date).getTime()+15552E6),path:"/"})}catch(j){}}},trimCookie:function(){var a=f.cookie("acta"),c=new Date-0,b,d,h;if(a)try{a=f.JSONParse(a);for(b in a)for(h in d=a[b],d)d[h][1]<c&&delete d[h];f.cookie("acta",f.JSONStringify(a),{domain:g,expires:new Date((new Date).getTime()+
15552E6),path:"/"})}catch(e){}},zcookie:function(a,c,b){var d=this.mid,h=new Date-0,e;a=="actmapping"&&(d=0);b=b&&b.expires?b.expires.getTime():2592E6;if(e=f.cookie("acta"))try{e=f.JSONParse(e)}catch(i){}if(typeof c!=="undefined"){e?e[a]||(e[a]={}):(e={},e[a]={});e[a][d]=[c,b];try{f.cookie("acta",f.JSONStringify(e),{domain:g,expires:new Date((new Date).getTime()+15552E6),path:"/"})}catch(j){}}else return e&&e[a]&&e[a][d]?(a=e[a][d],a[1]>h?a[0]:null):null},track:function(a){var c=this;(function(){if(f.idle[1]){var b=
c.getServerUrl()+c.getParameters(a),d=function(){f.idle[1]=1};f.idle[1]=0;c.cer=a;f.load(b,1,d,1E4,d)}else setTimeout(arguments.callee,0)})()},generateCurrentUrl:function(a){var c="";try{c=a.indexOf("/")==0?top.location.protocol+"//"+top.location.host+a:/^https?:\/\//.test(a)?a:top.location.protocol+"//"+top.location.host+top.location.pathname.slice(0,top.location.pathname.lastIndexOf("/"))+"/"+a}catch(b){c=a.indexOf("/")==0?location.protocol+"//"+location.host+a:/^https?:\/\//.test(a)?a:location.protocol+
"//"+location.host+location.pathname.slice(0,location.pathname.lastIndexOf("/"))+"/"+a}return encodeURIComponent(c)},getParameters:function(a){var c,b={rct:"html",g:0,mid:this.mid,st:this.st,u:[f.getCookieEnabled(),f.getFlashVersion()].join(","),sr:[screen.width,screen.height].join(","),dt:""},d=this.zcookie("actis"),g=this.zcookie("acts"),e=this.zcookie("actn"),i=this.zcookie("acti");if(d)d=d.split(">"),b.aid=d[1],b.bid=d[2],b.cid=d[3];if(g)g=g.split(">"),b.src=g.join(",");if(e&&(e=e.split(">"),
e[0]!=0))b.ssn=e.join(",");if(this.ecc)b.curl=encodeURIComponent(document.referrer);a.path&&a.type==="pageview"?(b.purl=this._purl||f.getCurrentUrl(),b.curl=this.generateCurrentUrl(a.path),this._purl=b.curl,a.path=null):b.purl=f.getPreviousUrl();b.jsv=this.jsv;if(typeof a==="object")for(c in a)a.hasOwnProperty(c)&&a[c]!==""&&a[c]!=k&&(this.mid===500093?b[c]=encodeURIComponent(a[c]):b[c.toLowerCase()]=encodeURIComponent(a[c]));if(f.cookie("__utmz"))b.gac=f.cookie("__utmz");if(i)b.fvid=i;return f.joinParameters(b,
"&")},s:function(a,c,b,d,f,e,i,j,k,l){switch(a){case 1:this.zcookie("actis",[a,c||0,b||0,d||0].join(">"),{domain:g,expires:new Date((new Date).getTime()+2592E6),path:"/"});this.zcookie("acts",[a,encodeURIComponent(c||0),encodeURIComponent(b||0),encodeURIComponent(d||0),f||0,e||0,encodeURIComponent(i||""),encodeURIComponent(j||""),encodeURIComponent(k||""),encodeURIComponent(l||"")].join(">"),{domain:g,expires:new Date((new Date).getTime()+15552E6),path:"/"});break;case 2:this.zcookie("acts",[a,encodeURIComponent(c||
""),encodeURIComponent(b||""),encodeURIComponent(d||""),encodeURIComponent(f||""),encodeURIComponent(e||"")].join(">"),{domain:g,expires:new Date((new Date).getTime()+15552E6),path:"/"});break;case 3:this.zcookie("acts",[a,encodeURIComponent(c||""),encodeURIComponent(b||"")].join(">"),{domain:g,expires:new Date((new Date).getTime()+15552E6),path:"/"});break;case 4:this.zcookie("acts",[a,encodeURIComponent(c||"")].join(">"),{domain:g,expires:new Date((new Date).getTime()+15552E6),path:"/"});break;
case 5:this.zcookie("acts",""+a,{domain:g,expires:new Date((new Date).getTime()+15552E6),path:"/"});break;case 6:this.zcookie("actis",[a,c||0,b||0,d||0].join(">"),{domain:g,expires:new Date((new Date).getTime()+2592E6),path:"/"}),this.zcookie("acts",[a,c||0,b||0,d||0,encodeURIComponent(f||""),encodeURIComponent(e||""),encodeURIComponent(i||""),encodeURIComponent(j||""),encodeURIComponent(k||"")].join(">"),{domain:g,expires:new Date((new Date).getTime()+15552E6),path:"/"})}},n:function(a,c,b){var d=
this.zcookie("actn");d&&(d=d.split(">"),d[0]!=a&&(d[1]=0,d[3]=0),this.cer.type==="pageview"&&(d[3]=parseInt(d[3],10)+1,d[4]=c),d[6]||(d[6]=c),d[0]=a,d[1]=parseInt(d[1],10)+1,d[2]=c,d[5]=b||0,this.zcookie("actn",d.join(">"),{domain:g,expires:new Date((new Date).getTime()+15552E6),path:"/"}),this.zcookie("actmapping")||f.mappimg(),this.zcookie("actmapping",1,{domain:g,expires:new Date((new Date).getTime()+2592E6),path:"/"}))},getServerUrl:function(){return this.mid===500093?(location.protocol==="https:"?
"https://":"http://")+this.getBaseUrl()+"nact.htm?":(location.protocol==="https:"?"https://":"http://")+this.getBaseUrl()+(location.protocol==="https:"?"snact.htm?":"nact.htm?")},getBaseUrl:function(){return this.serverbaseurl?this.serverbaseurl:this.mid===500093?location.protocol==="https:"?"secure.acs86.com/":"acs86.com/":location.protocol==="https:"?"secure.acs86.com/":"minisite.acs86.com/"}};f.prototype.init.prototype=f.prototype}})();
typeof ACTrackerz!=="undefined"&&ACTrackerz.constructor!=="_ACTrackerz"&&(ACTrackerz=_ACTrackerz(ACTrackerz));
